project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ".."
preserve_hierarchy: false
files:
  - source: src/Tippy/Tippy/Resource/source/Tippy_Localizable.json
    translation: src/Tippy/Tippy/Resource/translation/%two_letters_code%.json